#ifndef PLUGINWEBGOOGLE_GLOBAL_H
#define PLUGINWEBGOOGLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGINWEBGOOGLE_LIBRARY)
#  define PLUGINWEBGOOGLE_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINWEBGOOGLE_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINWEBGOOGLE_GLOBAL_H
